[package]
name = "gratte_nostd_tests"
version.workspace = true
authors.workspace = true
edition = "2021"
rust-version = "1.66.1"

publish = false

[dependencies]
gratte = { workspace = true }
gratte_macros = { workspace = true }

[dev-dependencies]
rustversion = { workspace = true }
